package mx.com.fca.unam.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ECommerceViewBuild extends javax.swing.JFrame {
    
    public ECommerceViewBuild() {
        
        initComponents();
        setLocationRelativeTo(null);
        returnPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserLabel = new javax.swing.JLabel();
        createUserLabel1 = new javax.swing.JLabel();
        createUserLabel2 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        nameECommerceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createUserLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        createUserLabel.setText("Espere la siguiente liberación.");

        createUserLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        createUserLabel1.setText("¡Disculpe la molestía!");

        createUserLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        createUserLabel2.setText("Estamos construyedo la aplicación.");

        returnButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        returnButton.setText("Regresar");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        nameECommerceLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nameECommerceLabel.setText("Amazon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createUserLabel2)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createUserLabel)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createUserLabel1)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameECommerceLabel)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(nameECommerceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(createUserLabel1)
                .addGap(30, 30, 30)
                .addComponent(createUserLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createUserLabel)
                .addGap(28, 28, 28)
                .addComponent(returnButton)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createUserLabel;
    private javax.swing.JLabel createUserLabel1;
    private javax.swing.JLabel createUserLabel2;
    private javax.swing.JLabel nameECommerceLabel;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables

    private void returnPage() {
         ActionListener button = new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 setVisible(false);
             }
         };
         returnButton.addActionListener(button);
    }
}
